Post Criando seu cluster Kubernetes com apenas um comando
buteco-tech/blog pull request #17
Opened 2020-08-24 21:06 UTC by jaswdr

2020-08-24 22:37 UTC, alexandrevicenzi requested changes

2020-08-24 22:37 UTC, alexandrevicenzi commented on content/posts/2020-08-29-criando-cluster-kubernetes-com-um-comando.md
> +summary: "Criar um cluster Kubernetes pronto para produção pode não ser simples, veja como criar um usando apenas um único comando."
Criar um cluster Kubernetes pronto para uso em produção não costuma ser simples, veja como criar um cluster usando apenas um único comando.

2020-08-24 22:37 UTC, alexandrevicenzi commented on content/posts/2020-08-29-criando-cluster-kubernetes-com-um-comando.md
> +title: "Criando seu cluster Kubernetes com apenas um comando"
Crie um cluster Kubernetes com apenas um comando com o eksctl

2020-08-24 22:37 UTC, alexandrevicenzi commented on content/posts/2020-08-29-criando-cluster-kubernetes-com-um-comando.md
> +tagline: "Criar cluster kubernetes com apenas um comando"
Eu acho que tagline nesse fica mto repetitivo, tagline é bom quando tu quer usar um subtitilo

2020-08-24 22:37 UTC, alexandrevicenzi commented on content/posts/2020-08-29-criando-cluster-kubernetes-com-um-comando.md
> +  - Desenvolvimento
Adicionar Ferramentas talvez?

2020-08-24 22:37 UTC, alexandrevicenzi commented on content/posts/2020-08-29-criando-cluster-kubernetes-com-um-comando.md
> +  - kubernetes
so uma tag? acho que da pra colocar algo a mais, cloud computing, aws, etc

2020-08-24 22:37 UTC, alexandrevicenzi commented on content/posts/2020-08-29-criando-cluster-kubernetes-com-um-comando.md
> +- /images/posts/k8s-logo.png
eks tem logo propria

2020-08-24 22:37 UTC, alexandrevicenzi commented on content/posts/2020-08-29-criando-cluster-kubernetes-com-um-comando.md
> +tagline: "Criar cluster kubernetes com apenas um comando"
Configurando um cluster na AWS de forma simples e fácil

2020-08-24 22:37 UTC, alexandrevicenzi commented on content/posts/2020-08-29-criando-cluster-kubernetes-com-um-comando.md
> +> Importante: O `eksctl` é focado na nuvem AWS e para poder criar todos os recursos necessários você precisará de uma conta com as permissões corretas.
Move pra cima, antes de Bash

2020-08-24 22:37 UTC, alexandrevicenzi commented on content/posts/2020-08-29-criando-cluster-kubernetes-com-um-comando.md
> +Depois de instalado, podemos criar nosso cluster usando o comando `eksctl create cluster`, porém esse comando irá usar uma série de parametros padrões que possivelmente não atenderá a sua necessidade
atenderão a sua necesssidade... plural fica melhor

2020-08-24 22:37 UTC, alexandrevicenzi commented on content/posts/2020-08-29-criando-cluster-kubernetes-com-um-comando.md
> +- `-t`: determina o tipo de instância, o tipo irá determinar fatores como quantidade de CPU e memória, instâncias do tipo `t3.medium` como é o caso do exemplo possuem 2 vCPUs e 4Gb de memória ram, um
instancia. O tipo...

2020-08-24 22:37 UTC, alexandrevicenzi commented on content/posts/2020-08-29-criando-cluster-kubernetes-com-um-comando.md
> +- `--ssh-access`: permite acesso via protocolo `ssh` a cada instância, isso pode lhe ajudar caso queira realizar algum debug, por padrão esse acesso é desativado.
isso pode ser util caso...

2020-08-24 22:37 UTC, alexandrevicenzi commented on content/posts/2020-08-29-criando-cluster-kubernetes-com-um-comando.md
> +- `--external-dns-access`: exporta e libera o acesso externo a provedores de DNS, permitindo que suas instâncias recebam trafego externo.
tráfego

2020-08-24 22:37 UTC, alexandrevicenzi commented on content/posts/2020-08-29-criando-cluster-kubernetes-com-um-comando.md
> +- `--full-ecr-access`: habilita a integração com o serviço ECR da AWS, podendo por exemplo usar repositórios privados de imagens de containers.
podendo por exemplo, usar...

2020-08-24 22:37 UTC, alexandrevicenzi commented on content/posts/2020-08-29-criando-cluster-kubernetes-com-um-comando.md
> +Executando o comando acima teremos algumas informações sendo impressas no terminal.
Impressas? soa estranho, pq é no terminal

2020-08-24 22:37 UTC, alexandrevicenzi commented on content/posts/2020-08-29-criando-cluster-kubernetes-com-um-comando.md
> +Dentre diversas informações, podemos ver que a ultima mensagem indica que o cluster `exemplo` na região `eu-west-1` está pronto, para provar isso podemos testar alguns comandos, perceba que foi gerad
última, penúltima

2020-08-24 22:37 UTC, alexandrevicenzi commented on content/posts/2020-08-29-criando-cluster-kubernetes-com-um-comando.md
> +Dentre diversas informações, podemos ver que a ultima mensagem indica que o cluster `exemplo` na região `eu-west-1` está pronto, para provar isso podemos testar alguns comandos, perceba que foi gerad
falta acento

2020-08-24 22:37 UTC, alexandrevicenzi commented on content/posts/2020-08-29-criando-cluster-kubernetes-com-um-comando.md
> +Por fim temos nosso cluster, com 3 nodes e pronto para produção e pronto para você usar todos os comandos disponíveis do `kubectl`.
...pronto para uso em produção e disponível para usar com todos os comandos do kubectl...

soa melhor

2020-08-24 22:37 UTC, alexandrevicenzi commented on content/posts/2020-08-29-criando-cluster-kubernetes-com-um-comando.md
> +O `eksctl` possui varias outras opções, como escalar para aumentar ou diminuir a quantidade de hosts ou criar um auto-scale para que isso seja feito de forma automática, contudo isso é algo que você
várias

2020-08-24 22:38 UTC, alexandrevicenzi commented on content/posts/2020-08-29-criando-cluster-kubernetes-com-um-comando.md
> +date: 2020-08-29 08:00:00
Sábado? melhor quinta talvez

2020-08-24 22:40 UTC, alexandrevicenzi commented on content/posts/2020-08-29-criando-cluster-kubernetes-com-um-comando.md
> +- /images/posts/k8s-logo.png
usa logo da waveworks que ta no site do eksctl ou logo do EKS mesmo

2020-08-25 11:24 UTC, jaswdr commented on content/posts/2020-08-29-criando-cluster-kubernetes-com-um-comando.md
> +title: "Criando seu cluster Kubernetes com apenas um comando"
pensei em colocar isso inicialmente, mas acredito que tirar o eksctl fica mais "apelativo"

2020-08-25 11:36 UTC, jaswdr commented
@prscheduler 27/08/2020T12:00

2020-08-25 17:59 UTC, alexandrevicenzi requested changes

2020-08-25 17:59 UTC, alexandrevicenzi commented on content/posts/2020-08-27-criando-cluster-kubernetes-com-um-comando.md
> +  - cloud
cloud computing em uma linha, senao fica 2 tags, ta estranho

2020-08-25 17:59 UTC, alexandrevicenzi commented on content/posts/2020-08-27-criando-cluster-kubernetes-com-um-comando.md
> +> Importante: O `eksctl` é focado na nuvem AWS e para poder criar todos os recursos necessários você precisará de uma conta com as permissões corretas.
Não quis mover?

2020-08-25 17:59 UTC, alexandrevicenzi commented on content/posts/2020-08-27-criando-cluster-kubernetes-com-um-comando.md
> +- `--external-dns-access`: exporta e libera o acesso externo a provedores de DNS, permitindo que suas instâncias recebam trafego externo.
trafego vai acento, tráfego, não?

2020-08-25 19:02 UTC, jaswdr commented on content/posts/2020-08-27-criando-cluster-kubernetes-com-um-comando.md
> +> Importante: O `eksctl` é focado na nuvem AWS e para poder criar todos os recursos necessários você precisará de uma conta com as permissões corretas.
vi agora os itens que faltaram, corrigi esse ponto também

2020-08-25 19:15 UTC, alexandrevicenzi approved these changes

2020-08-27 12:00 UTC, merged