Post Conhecendo Docker
buteco-tech/blog pull request #26
Opened 2020-09-24 08:11 UTC by jaswdr

2020-09-24 08:52 UTC, alexandrevicenzi requested changes

2020-09-24 08:52 UTC, alexandrevicenzi commented on content/posts/2020-10-02-conhecendo-docker.md
> +summary: "Learn about the complete container solution provided by Docker. Find information for developers, IT operations, and business executives."
Ta em ingles

2020-09-24 08:52 UTC, alexandrevicenzi commented on content/posts/2020-10-02-conhecendo-docker.md
> +tagline: "Learn about the complete container solution provided by Docker. Find information for developers, IT operations, and business executives."
Tagline é pra ser curtinha, menos de 100 chars

2020-09-24 08:52 UTC, alexandrevicenzi commented on content/posts/2020-10-02-conhecendo-docker.md
> +  - Ferramentas
Acho que nao precisa da categoria Ferramentas

2020-09-24 08:52 UTC, alexandrevicenzi commented on content/posts/2020-10-02-conhecendo-docker.md
> +O Docker é uma ferramenta criada para facilitar o uso de contêineres, algo que não é tão novo no mundo Linux, uma vez que projetos como o LXC já existe a muitos anos, porém o seu uso é complexo e a c
O Docker é uma ferramenta criada para facilitar o uso de contêineres, algo que não é tão novo no mundo Linux, uma vez que projetos como o LXC já existe**m** a muitos anos, porém o seu uso é complexo e a curva de aprendizado é bastante grande. **Foi** para resolver este e outros problemas que o `Docker` nasceu. Inicialmente criado por uma empresa independente, teve tanto sucesso que a própria empresa mudou seu nome posteriormente para `Docker Inc.`.

2020-09-24 08:52 UTC, alexandrevicenzi commented on content/posts/2020-10-02-conhecendo-docker.md
> +Mas por que você deveria se importar com contêineres? Existe uma série de motivos que fazem os contêineres serem interessantes e uma melhor alternativa que as máquinas virtuais. O principal motivo é
HOST = maquina hospedeira (talvez)

2020-09-24 08:52 UTC, alexandrevicenzi commented on content/posts/2020-10-02-conhecendo-docker.md
> +Mas por que você deveria se importar com contêineres? Existe uma série de motivos que fazem os contêineres serem interessantes e uma melhor alternativa que as máquinas virtuais. O principal motivo é
overhead pode ser tradudizo pra sobrecarga

2020-09-24 08:52 UTC, alexandrevicenzi commented on content/posts/2020-10-02-conhecendo-docker.md
> +Mas por que você deveria se importar com contêineres? Existe uma série de motivos que fazem os contêineres serem interessantes e uma melhor alternativa que as máquinas virtuais. O principal motivo é
Acho que pode por um link para https://butecotecnologico.com.br/de-que-sao-feitos-containers-linux/ caso alguem queira saber mais e mencionar no texto, backlink é bom

2020-09-24 08:52 UTC, alexandrevicenzi commented on content/posts/2020-10-02-conhecendo-docker.md
> +Outra questão muito importante que nem sempre é considerado quando se usa máquinas virtuais, é que contêineres são efêmeros, ou seja, um contêiner não deve armazenar dados importantes em seu `filesys
muito importante -> importante

muito fica meio feio e informal

2020-09-24 08:52 UTC, alexandrevicenzi commented on content/posts/2020-10-02-conhecendo-docker.md
> +Aprenda neste tutorial como você pode usar e aproveitar o máximo do Docker no seu dia a dia como desenvolvedor de software.
Aprenda neste tutorial como usar e aproveitar o máximo do Docker no seu dia a dia como desenvolvedor de software.

2020-09-24 08:52 UTC, alexandrevicenzi commented on content/posts/2020-10-02-conhecendo-docker.md
> +$ curl -fsSL https://get.docker.io | bash
oh boy, melhor instalar com apt, dnf e afins IMHO

poderia mencionar para procurar no gerenciador de pacotes

2020-09-24 08:52 UTC, alexandrevicenzi commented on content/posts/2020-10-02-conhecendo-docker.md
> +$ curl -fsSL https://get.docker.io | bash
ok, o script ate instala em distros usando o gerenciador, mas so debian, ubuntu, centos e rhel

2020-09-24 08:52 UTC, alexandrevicenzi commented on content/posts/2020-10-02-conhecendo-docker.md
> +A instalação no Windows e Mac são bem simples, basta seguir o passo a passo que você fará a instalação do Docker Desktop, essa aplicação funciona de forma diferente, como o docker é nativo apenas de
basta seguir o passo a passo que você fará a instalação do Docker Desktop, ein?

basta seguir o passo a passo para realizar a instalação do Docker Desktop

2020-09-24 08:52 UTC, alexandrevicenzi commented on content/posts/2020-10-02-conhecendo-docker.md
> +O comando acima execute o subcomando `run` que basicamente cria e executa um novo contêiner. O único parâmetro que realmente é obrigatório para executar um contêiner é o nome da imagem do contêiner.
O comando acima execut**a**

2020-09-24 08:52 UTC, alexandrevicenzi commented on content/posts/2020-10-02-conhecendo-docker.md
> +O comando acima execute o subcomando `run` que basicamente cria e executa um novo contêiner. O único parâmetro que realmente é obrigatório para executar um contêiner é o nome da imagem do contêiner.
standalone da pra ser traduzido?

2020-09-24 08:52 UTC, alexandrevicenzi commented on content/posts/2020-10-02-conhecendo-docker.md
> +Além do que vimos acima existem diversos outros conceitos importantes que você deve saber antes de começar a usar o docker, ou até mesmo para usar todo o potêncial do mesmo.
Além do que vimos acima **,** <-

2020-09-24 08:52 UTC, alexandrevicenzi commented on content/posts/2020-10-02-conhecendo-docker.md
> +A principio nada de mais parece ter mudado, mas vá para o diretório `/exemplo` usando o `cd`.
principio tem acento

2020-09-24 08:52 UTC, alexandrevicenzi commented on content/posts/2020-10-02-conhecendo-docker.md
> +Digamos que você queira rodar o servidor NGINX, para isso basta executar o comando abaixo:
NGINX é Nginx o correto ate onde sei

2020-09-24 08:52 UTC, alexandrevicenzi commented on content/posts/2020-10-02-conhecendo-docker.md
> +Perceba o uso da flag `-p` passando o valor `8080:80`, isso significa que está sendo feito um vinculo, ou *bind*, da porta 8080 local com a porta 80 do contêiner, fazendo com que requisições que seja
Poderia mencionar que so da pra fazer bind uma unica vez, 2 docker nao pode usar a mesma porta

2020-09-24 08:52 UTC, alexandrevicenzi commented on content/posts/2020-10-02-conhecendo-docker.md
> +Python 2.7
ô meu fío, 2.7 morreu, pode remover isso

2020-09-24 08:52 UTC, alexandrevicenzi commented on content/posts/2020-10-02-conhecendo-docker.md
> +Python 3.6
3.8 é o atual :)

2020-09-24 08:52 UTC, alexandrevicenzi commented on content/posts/2020-10-02-conhecendo-docker.md
> +# Conclusão
what, cade a conclusao? acho que poderia fazer um paragrafo mencionando o quao bom o docker é e porque alguem deveria usar :)

2020-09-24 08:52 UTC, alexandrevicenzi commented on content/posts/2020-10-02-conhecendo-docker.md
> +title: "Conhecendo o Docker"
Na verdade é um "Tutorial de Docker"

2020-09-24 08:52 UTC, alexandrevicenzi commented on content/posts/2020-10-02-conhecendo-docker.md
> +tagline: "Learn about the complete container solution provided by Docker. Find information for developers, IT operations, and business executives."
"Conhecendo o Docker com exemplos práticos"

2020-09-24 08:52 UTC, alexandrevicenzi commented on content/posts/2020-10-02-conhecendo-docker.md
> +summary: "Learn about the complete container solution provided by Docker. Find information for developers, IT operations, and business executives."
Você sabe o que é Docker e como usá-lo? Neste tutorial explicamos um pouco sobre o Docker, como instalá-lo no Linux, Windows e Mac, além de exemplificar alguns comandos com exemplos práticos.

2020-09-24 08:52 UTC, alexandrevicenzi commented on content/posts/2020-10-02-conhecendo-docker.md
> +O Docker é uma ferramenta criada para facilitar o uso de contêineres, algo que não é tão novo no mundo Linux, uma vez que projetos como o LXC já existe a muitos anos, porém o seu uso é complexo e a c
O Docker é um conjunto de ferrametas...

2020-09-24 08:52 UTC, alexandrevicenzi commented on content/posts/2020-10-02-conhecendo-docker.md
> +slug: conhecendo-docker
se mudar o titulo muda a slug pra "tutorial-de-docker"

2020-09-25 08:48 UTC, jaswdr commented
@alexandrevicenzi feito correções

2020-09-25 11:20 UTC, jaswdr commented on content/posts/2020-10-02-conhecendo-docker.md
> +O comando acima execute o subcomando `run` que basicamente cria e executa um novo contêiner. O único parâmetro que realmente é obrigatório para executar um contêiner é o nome da imagem do contêiner.
não achei uma tradução viável para `standalone`

2020-09-25 11:35 UTC, jaswdr commented
@prscheduler 02/10/2020T12:00

2020-09-30 12:46 UTC, alexandrevicenzi requested changes
So um detalhe bobo

2020-09-30 12:46 UTC, alexandrevicenzi commented on content/posts/2020-10-02-tutorial-de-docker.md
> +E ai gostou do docker? quer ver mais conteúdo sobre, tem alguma sugestão? comente abaixo e nos vemos na próxima.
depois de ? se usa maiscula nao?

2020-09-30 12:51 UTC, jaswdr commented
@prscheduler 01/10/2020T12:00

2020-09-30 15:03 UTC, alexandrevicenzi commented on content/posts/2020-10-02-tutorial-de-docker.md
> +E ai gostou do docker? Quer ver mais conteúdo sobre, tem alguma sugestão? comente abaixo e nos vemos na próxima.
Ainda faltou o ? Comente

2020-09-30 15:05 UTC, alexandrevicenzi approved these changes

2020-10-01 12:00 UTC, merged