Criado artigo sobre Git e GitHub
buteco-tech/blog pull request #31
Opened 2020-10-08 22:13 UTC by LeoDalcegio

2020-10-09 12:09 UTC, alexandrevicenzi requested changes
Esse artigo foca em Windows, e sinceramente o blog foca no mundo Linux e Software Livre.

Não sou contra Windows, mas prefiro algo generico que pode ser usado por todos, ou faz um artigo especifico pra cada SO, e no Windows tem ferramentas melhores que linha de comando até.

Eu acho que o tutorial segue um fluxo de trabalho que quase ninguem usa, geralmente começamos pelo GitHub, e fazemos clone, por que em muitos casos começamos em projetos que ja existem.

O artigo também nao ensina nada sobre ssh, ninguem gosta de ficar digitando senha a todo push.

2020-10-09 12:09 UTC, alexandrevicenzi commented on content/posts/2020-10-08-aprenda-git-e-github-com-este-artigo.md
> +title: "Aprenda Git e GitHub com este artigo"
"Tutorial de Git e GitHub" soa melhor

2020-10-09 12:09 UTC, alexandrevicenzi commented on content/posts/2020-10-08-aprenda-git-e-github-com-este-artigo.md
> +slug: aprenda-git-e-github-com-este-artigo
tutorial-git-e-github

2020-10-09 12:09 UTC, alexandrevicenzi commented on content/posts/2020-10-08-aprenda-git-e-github-com-este-artigo.md
> +  - hacktoberfest
hacktoberfest nao faz sentido aqui

2020-10-09 12:09 UTC, alexandrevicenzi commented on content/posts/2020-10-08-aprenda-git-e-github-com-este-artigo.md
> +  - /images/posts/git-logo.png
so coloca a logo, as outras images nao deveriam estar aqui

2020-10-09 12:09 UTC, alexandrevicenzi commented on content/posts/2020-10-08-aprenda-git-e-github-com-este-artigo.md
> +Se você é ou pretende se tornar um desenvolvedor, já deve ter ouvido falar do **Git** e **GitHub**, um sistema do controle de versão e um repositório online para os nossos projetos. Agora é a hora de
git e github deveriam ser links e nao negrito.

2020-10-09 12:09 UTC, alexandrevicenzi commented on content/posts/2020-10-08-aprenda-git-e-github-com-este-artigo.md
> +Se você vai utilizar Git, provavelmente vai querer armazenar o seu repositório em algum lugar, existem duas formas de se fazer isso, offline, no seu próprio computador, e online, em alguma plataforma
github, bitbucket, gitlab poderiam ser links

2020-10-09 12:09 UTC, alexandrevicenzi commented on content/posts/2020-10-08-aprenda-git-e-github-com-este-artigo.md
> +E é exatamente para isso que o GitHub serve, para armazenar seu repositório nele, é o Google Drive dos códigos.
Junta com o paragrafo de cima

2020-10-09 12:09 UTC, alexandrevicenzi commented on content/posts/2020-10-08-aprenda-git-e-github-com-este-artigo.md
> +Existem muitas outras funcionalidades dele, como as **"Pull Requests"** por exemplo, mas isso é um assunto para outro dia.
ta fraco essa frase, remove ou fala mais sobre as features.

2020-10-09 12:09 UTC, alexandrevicenzi commented on content/posts/2020-10-08-aprenda-git-e-github-com-este-artigo.md
> +E o GitHub você cria uma conta [aqui](https://github.com/).
Junta essas linhas em um ou 2 paragrafos, senao fica muito estranho tudo solto.

No Linux costuma-se instalar via gerenciador de pacotes, poderia mencionar isso.

2020-10-09 12:09 UTC, alexandrevicenzi commented on content/posts/2020-10-08-aprenda-git-e-github-com-este-artigo.md
> +Agora chegou a hora de criar o seu repositório Git localmente, para depois subir ele ao GitHub.
Ao usar algo como GitHub geralmente se cria no GH e depois se faz o clone localmente.

2020-10-09 12:09 UTC, alexandrevicenzi commented on content/posts/2020-10-08-aprenda-git-e-github-com-este-artigo.md
> +Agora, navegue até ela com o seu terminal, ou clique com o botão direito sobre ela e selecione **"Git Bash Here"** (irá abrir o terminal do git dentro dela).
Isso é muito Windows, o artigo deveria ser inferente se é Linux, Windows ou Mac

2020-10-09 12:09 UTC, alexandrevicenzi commented on content/posts/2020-10-08-aprenda-git-e-github-com-este-artigo.md
> +No momento em que escrevo este artigo, está acontecendo a **Hacktoberfest** um evento muito massa da [Digital Ocean](https://www.digitalocean.com/), aqui vai um artigo do [Buteco Técnologico](http://
pode remover esse texto eu acho e o link ta localhost

2020-10-09 12:09 UTC, alexandrevicenzi commented on content/posts/2020-10-08-aprenda-git-e-github-com-este-artigo.md
> +Caso você tenha acabado de instalar o Git no seu computador, talvez seja necessário configurar o seu email e nome, que será exibido em seus commits.
Talvez nao, é preciso, e deveria ser o primeiro passo a ser feito, antes mesmo de um git init

2020-10-09 12:09 UTC, alexandrevicenzi commented on content/posts/2020-10-08-aprenda-git-e-github-com-este-artigo.md
> +Digite o comando "git init" no terminal, ele irá inicializar o seu repositório e criar uma pasta chamada **".git"**, caso você não consiga ver essa pasta, é por que você não consegue ver arquivos ocu
Coisa especifica do Windows

2020-10-09 12:09 UTC, alexandrevicenzi commented on content/posts/2020-10-08-aprenda-git-e-github-com-este-artigo.md
> +É dentro dessa pasta ".git" que ficarão os arquivos que [comitaremos](https://pt.wikipedia.org/wiki/Commit) no nosso repositório.
Essa frase não é verdade, os arquivos ficam no repositorio, na raiz, o .git faz track das alteraçoes

2020-10-09 12:09 UTC, alexandrevicenzi commented on content/posts/2020-10-08-aprenda-git-e-github-com-este-artigo.md
> +Essas são as alterações pendentes, elas ainda não estão dentro da pasta **".git"**, para colocarmos elas lá, precisamos comitar as alterações, mas antes de comitar, precisamos definir o que é que que
esse comentario que fica na pasta .git nao é bem certo

2020-10-09 12:09 UTC, alexandrevicenzi commented on content/posts/2020-10-08-aprenda-git-e-github-com-este-artigo.md
> +- **git remote add origin https://github.com/usuario-github/repositorio.git**
https pede senha toda vida, o certo é usar ssh, e o artigo nem menciona como criar uma chave ssh nem como configura-la

2020-10-09 13:07 UTC, LeoDalcegio commented
Obrigado pela revisão, vou realizar as alterações

2020-10-09 13:22 UTC, LeoDalcegio commented on content/posts/2020-10-08-aprenda-git-e-github-com-este-artigo.md
> +Agora, navegue até ela com o seu terminal, ou clique com o botão direito sobre ela e selecione **"Git Bash Here"** (irá abrir o terminal do git dentro dela).
Realmente acabei indo muito para o lado do Windows por ser o SO que eu uso, vou revisar essas partes também.

2020-10-09 13:22 UTC, LeoDalcegio commented on content/posts/2020-10-08-aprenda-git-e-github-com-este-artigo.md
> +No momento em que escrevo este artigo, está acontecendo a **Hacktoberfest** um evento muito massa da [Digital Ocean](https://www.digitalocean.com/), aqui vai um artigo do [Buteco Técnologico](http://
Ihhh verdade rsrsrs

2020-10-09 15:55 UTC, LeoDalcegio commented
Estou alterando um pouco o artigo, falasse do fluxo de trabalho, fiz dessa forma pois pensei que para algum iniciante seja mais simples de ele entender só fazendo localmente com o git init e depois subindo as alterações ao github. Mas pensando bem, fazer algo que ele possa fazer um clone de um repositório e até um pull request seja melhor, fica mais parecido com o dia-a-dia assim, fiz algumas alterações mas não está tudo terminado ainda. Ah e vou falar sobre SSH e configurar ela também.

2020-10-13 15:03 UTC, alexandrevicenzi commented
@LeoDalcegio ensina no artigo como enviar um PR pro Blog do buteco, ou se quiser ate podemos criar um repositorio de testes pra usar no artigo, so me avisar que eu crio um novo.

2020-10-13 15:46 UTC, LeoDalcegio commented
Eu tava pensando em fazer um repo novo, pra só adicionar/editar um arquivo de texto e fazer uma PR da alteração, mas pode ser pro Blog também se quiseres.

O que achas de criar um repositório novo para as pessoas fazerem PRs nele? Acho que seria mais simples, mais direto ao ponto.



-------- Mensagem original --------
De : Alexandre Vicenzi <notifications@github.com>
Data: 13/10/2020 12:04 (GMT-03:00)
Para: ButecoOpenSource/blog <blog@noreply.github.com>
Cc: Leonardo Luís Dalcegio <leoodalcegio@hotmail.com>, Mention <mention@noreply.github.com>
Assunto: Re: [ButecoOpenSource/blog] Criado artigo sobre Git e GitHub (#31)


@LeoDalcegio<https://github.com/LeoDalcegio> ensina no artigo como enviar um PR pro Blog do buteco, ou se quiser ate podemos criar um repositorio de testes pra usar no artigo, so me avisar que eu crio um novo.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/ButecoOpenSource/blog/pull/31#issuecomment-707803003>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ALS34IJFAAYRR3RWMQS247LSKRT6PANCNFSM4SJKLRNQ>.

2020-10-19 15:54 UTC, alexandrevicenzi commented
@LeoDalcegio segue repositorio, https://github.com/buteco-tech/artigo-tutorial-git

2020-10-20 10:28 UTC, LeoDalcegio commented
> @LeoDalcegio segue repositorio, https://github.com/buteco-tech/artigo-tutorial-git

404, não tenho acesso a ele

2020-10-21 09:23 UTC, alexandrevicenzi commented
> 404, não tenho acesso a ele

ajustei, verifica agora

2020-10-22 10:29 UTC, LeoDalcegio commented
> > 404, não tenho acesso a ele
> 
> ajustei, verifica agora

Agora sim

2020-10-28 13:22 UTC, LeoDalcegio commented
@alexandrevicenzi opa, consegues dar uma revisada nele e ver como ficou?

2020-11-03 13:16 UTC, LeoDalcegio commented
@alexandrevicenzi  consegues dar uma revisada nele e ver como ficou?

2020-11-03 20:07 UTC, alexandrevicenzi reviewed
No geral ta legal, mas tem uns textos que podem melhorar as escrita, ta confuso. Um coisa que notei é texto grande com muita virgula. Separa em frases, coloca ponto.

Não revisei 100% ainda.

Outra coisa, tem imagens nao usadas, e mudamos a estrutura de artigos. Agora os artigos e imagens ficam tudo em uma unica pasta, fica mais facil de manter, confere o master.

2020-11-03 20:07 UTC, alexandrevicenzi commented on content/authors/leonardodalcegio/_index.md
> +avatar: https://avatars3.githubusercontent.com/u/48610849?s=460&u=b87b4da4bc8910952bc89fd151c6cbdbc6b724ed&v=4
O ideal seria o do gravatar porque fica vinculado pra sempre, a url do git eu acho que nao

2020-11-03 20:07 UTC, alexandrevicenzi commented on content/posts/2020-10-28-aprenda-git-e-github-com-este-artigo.md
> +- **git config --global user.name "Seu nome que será exibido"**
Acho que pode usar como exemplos "Buteco Tecnológico" e "git@buteco.tech"

2020-11-03 20:07 UTC, alexandrevicenzi commented on content/posts/2020-10-28-aprenda-git-e-github-com-este-artigo.md
> +  Caso esses o comando **"ls"** retorne algo com a extensão ".pub", você não precisa executar o comando **"ssh-keygen"**. Caso contrário, digite esse comando no seu terminal, o email que você inserir
Caso esses o comando <- nao faz sentido

Caso o comando...

2020-11-03 20:07 UTC, alexandrevicenzi commented on content/posts/2020-10-28-aprenda-git-e-github-com-este-artigo.md
> +  Caso esses o comando **"ls"** retorne algo com a extensão ".pub", você não precisa executar o comando **"ssh-keygen"**. Caso contrário, digite esse comando no seu terminal, o email que você inserir
O email nao precisa ser o mesmo, pode ser qualquer chave na verdade.

2020-11-03 20:07 UTC, alexandrevicenzi commented on content/posts/2020-10-28-aprenda-git-e-github-com-este-artigo.md
> +- **clip < ~/.ssh/id_rsa.pub**
Em vez de clip e xclip é mais facil dar um cat e copiar manualmente.

2020-11-03 20:07 UTC, alexandrevicenzi commented on content/posts/2020-10-28-aprenda-git-e-github-com-este-artigo.md
> +Irá pedir um nome do arquivo para salvar a chave, não escreva nada e aperte **enter** (será gerada uma com o nome "id_rsa"). Depois, informe uma **"passphrase"**, digite uma senha e confirme ela. Pro
O comando acima rrá pedir um nome do arquivo para salvar a chave, não escreva nada e aperte **enter** (será gerada uma com o nome "id_rsa"). Depois, informe uma senha (**passphrase**) e confirme ela. Pronto, você gerou uma chave SSH.

Se você navegar até o local onde a chave foi criada, você verá dois arquivos, "id_rsa" e "id_rsa.pub". O com a extensão "pub" é a chave pública, ou seja, a chave que você irá informar ao **GitHub**. O arquivo sem o ".pub" é a sua chave privada, mantenha-a segura.

Digite o seguinte comando no terminal para exibir o conteúdo da chave gerada:

2020-11-03 20:07 UTC, alexandrevicenzi commented on content/posts/2020-10-28-aprenda-git-e-github-com-este-artigo.md
> +Agora vá até [essa página](https://github.com/settings/keys), aqui você pode ver as chaves SSH associadas a sua conta. Clique então no botão **"New SSH Key"**. O título você pode escolher um, e em "k
Acesse a página de [SSH and GPG keys no GitHub](https://github.com/settings/keys) para poder associar novas chaves SSH a sua conta.

2020-11-03 20:07 UTC, alexandrevicenzi commented on content/posts/2020-10-28-aprenda-git-e-github-com-este-artigo.md
> +Você irá informar essa chave pública ao **GitHub**, e então todas as vezes que você quiser subir o seu código ao **GitHub** por exemplo, você usará a sua chave privada, para mostrar ao **GitHub** que
Muda tudo, ta muito estranho, melhor dessa forma:

A chave pública é a qual você deve cadastrar no GitHub, com ela não será possível fazer usar o git via linha de comando sem a necessidade de senhas.

2020-11-03 20:07 UTC, alexandrevicenzi commented on content/posts/2020-10-28-aprenda-git-e-github-com-este-artigo.md
> +Depois de informado a sua chave **pública** ao **GitHub**, vamos agora adicionar a sua chave **privada** ao **ssh-agent**, um programa que fará a autenticação da sua máquina local, com o servidor rem
Eu faria tudo primeiro, depois iria pro GitHub, senão é um vai e volta e pode dar confusão.

2020-11-03 20:07 UTC, alexandrevicenzi commented on content/posts/2020-10-28-aprenda-git-e-github-com-este-artigo.md
> +## Workflow
So fork? Seria legal ensinar fork e como criar um repo novo

2020-11-04 22:15 UTC, LeoDalcegio commented
@alexandrevicenzi realizei as alterações aí

2020-11-05 22:09 UTC, LeoDalcegio commented
@alexandrevicenzi realizei as alterações aí

2020-11-06 08:42 UTC, jaswdr approved these changes

2020-11-06 10:38 UTC, LeoDalcegio commented
Tinha um subrepositório "git", sim, do git, não sei por que estava lá, foi eu quem criou.

Apenas exclui ele

2020-11-07 16:56 UTC, alexandrevicenzi requested changes
Existem vários erros de grafia que precisam ser corrigidos.

Existem varios estilos que precisam ser corrigidos:

- Palavras entre aspas deveriam ser negrito ou italico.
- Nome como Linux, Kernel, GitHub não precisam de aspas, nem italico, nem negrito.
- Palavras como publica e privada nao precisam de negrito.

Termos em Inglês devem ser em Itálicos, em vez de negritou ou aspas, usar o texto `*palavra*`

- commits
- pull request
- clone
- staging
- commitadas
- branches

Comandos bash devem usar o estilo `` `commando -x` ``

Eu coloquei alguns comentarios em umas linhas, mas o mesmo se aplica para o texto todo.

Eu coloquei alguns textos refeitos, ajustando frases por completo para facilitar.

2020-11-07 16:56 UTC, alexandrevicenzi commented on content/posts/2020/aprenda-git-e-github/index.md
> +Geralmente, o workflow de quando trabalhamos com **Git** e **GitHub**, é realizar um **fork** de um determinado repositório no **GitHub** de outra pessoa, dessa forma vamos estar com uma cópia desse
Erros de grafia:

repsitório -> repositório
reposítorio -> repositório

A palavra repositório é usada 6 vezes nesse texto.

2020-11-07 16:56 UTC, alexandrevicenzi commented on content/posts/2020/aprenda-git-e-github/index.md
> +Caso você nunca tenha viso algum desses nomes antes, não se assuste, pois vamos ver tudo isso neste artigo. Existe uma outra maneira de se trabalhar com o **git**, que veremos mais adiante, que é cri
Soa muito informal, e creio ser erro de conjugação.

pois vamos -> iremos

2020-11-07 16:56 UTC, alexandrevicenzi commented on content/posts/2020/aprenda-git-e-github/index.md
> +Caso você nunca tenha viso algum desses nomes antes, não se assuste, pois vamos ver tudo isso neste artigo. Existe uma outra maneira de se trabalhar com o **git**, que veremos mais adiante, que é cri
Existe uma outra maneira... -> Existe outra maneira...

2020-11-07 16:56 UTC, alexandrevicenzi commented on content/posts/2020/aprenda-git-e-github/index.md
> +Vamos agora clonar esse seu repositório para a sua máquina local, para que você possa realizar alterações nele Na página do seu repositório no GitHub, existe um botão chamado **"Code"**, clique nele,
Falta ponto antes de: Na página

2020-11-07 16:56 UTC, alexandrevicenzi commented on content/posts/2020/aprenda-git-e-github/index.md
> +Vamos criar um novo arquivo para que possamos comitar ele depois, então, crie um arquivo de texto com o seu nome por exemplo.
comitar -> adicionar

2020-11-07 16:56 UTC, alexandrevicenzi commented on content/posts/2020/aprenda-git-e-github/index.md
> +Voltando pro terminal , digite **"git status"**. Você verá essa mensagem:
Voltando pro terminal , digite... -> Voltando para o terminal, digite...

2020-11-07 16:56 UTC, alexandrevicenzi commented on content/posts/2020/aprenda-git-e-github/index.md
> +Então, digite **"git add ."**, para adicionar tudo. Se você quisesse adicionar apenas um arquivo por exemplo, daí seria **"git add nome-do-arquivo"**
Se você quisesse adicionar apenas um arquivo por exemplo, daí seria **"git add nome-do-arquivo"**

-> 

Se você quisesse adicionar apenas um arquivo, o comando seria **"git add nome-do-arquivo"**

2020-11-07 16:56 UTC, alexandrevicenzi commented on content/posts/2020/aprenda-git-e-github/index.md
> +Se você rodar um **"git status"**, o seu terminal deverá estar parecido com o abaixo.
Se você rodar um... -> Se você executar o comando....

2020-11-07 16:56 UTC, alexandrevicenzi commented on content/posts/2020/aprenda-git-e-github/index.md
> +Feito isso, é hora de subirmos essas alterações para o repositório remoto (que ainda não foi criado). Para isso, vá até a página do [GitHub](https://github.com/), e com a sua conta logada, clique no
Para isso, vá até a página do -> Para isso, visite a página do

2020-11-07 16:56 UTC, alexandrevicenzi commented on content/posts/2020/aprenda-git-e-github/index.md
> +Feito isso, é hora de subirmos essas alterações para o repositório remoto (que ainda não foi criado). Para isso, vá até a página do [GitHub](https://github.com/), e com a sua conta logada, clique no
osbre -> sobre

2020-11-07 16:56 UTC, alexandrevicenzi commented on content/posts/2020/aprenda-git-e-github/index.md
> +### Linkando o repositório local, ao remoto
Linkando? Essa palavra nao existe.

Talvez conectando ou vinculando soa melhor.

2020-11-07 16:56 UTC, alexandrevicenzi commented on content/posts/2020/aprenda-git-e-github/index.md
> +A primeira opção, é para criar um repositório local, linkar ele ao **GitHub**, e fazer um **push** das alterações. A segunda é para apenas linkar um repositório local já existente, e fazer um push de
Linkar talvez deveria ser conectar ou vincular.

2020-11-07 16:56 UTC, alexandrevicenzi commented on content/posts/2020/aprenda-git-e-github/index.md
> +Realize agora uma alteração, crie um arquivo de texto por exemplo. Depois, execute o comando **"git add"** que foi falado anteriormente e **"git commit -m"**, agora você já está craque nisso. Lembre-
Realize agora uma alteração, crie um arquivo de texto por exemplo.

-> 

Realize agora uma alteração. Crie um arquivo de texto, por exemplo.

2020-11-07 16:56 UTC, alexandrevicenzi commented on content/posts/2020/aprenda-git-e-github/index.md
> +date: 2020-11-04 08:00:00
Coloca a data la pro dia 18 ou 19

2020-11-07 16:56 UTC, alexandrevicenzi commented on content/posts/2020/aprenda-git-e-github/index.md
> +É necessário ter o Git instalado no seu computador e uma conta no GitHub criada.
É necessário possuir o Git instalado no seu computador e uma conta no GitHub.

2020-11-07 16:56 UTC, alexandrevicenzi commented on content/posts/2020/aprenda-git-e-github/index.md
> +Ambos os passos são bem rápidos, você pode baixar o Git [aqui](https://git-scm.com/downloads), é só selecionar o seu sistema operacional e seguir o setup, no caso do **Linux**, costuma-se instalar o
setup -> guia de instalação

2020-11-07 16:56 UTC, alexandrevicenzi commented on content/posts/2020/aprenda-git-e-github/index.md
> +Ambos os passos são bem rápidos, você pode baixar o Git [aqui](https://git-scm.com/downloads), é só selecionar o seu sistema operacional e seguir o setup, no caso do **Linux**, costuma-se instalar o
Linux não precisa de negrito.

2020-11-07 16:56 UTC, alexandrevicenzi commented on content/posts/2020/aprenda-git-e-github/index.md
> +Ambos os passos são bem rápidos, você pode baixar o Git [aqui](https://git-scm.com/downloads), é só selecionar o seu sistema operacional e seguir o setup, no caso do **Linux**, costuma-se instalar o
E o GitHub você cria uma conta aqui -> Já para o GitHub, você deve cria uma conta aqui

2020-11-07 16:56 UTC, alexandrevicenzi commented on content/posts/2020/aprenda-git-e-github/index.md
> +Depois de ter baixado o Git, é necessário configurar o seu nome e email que serão exibidos em seus commits, para isso é só digitar no terminal o seguinte (caso você esteja no Windows, não se esqueça
email -> e-mail

2020-11-07 16:56 UTC, alexandrevicenzi commented on content/posts/2020/aprenda-git-e-github/index.md
> +Depois de ter baixado o Git, é necessário configurar o seu nome e email que serão exibidos em seus commits, para isso é só digitar no terminal o seguinte (caso você esteja no Windows, não se esqueça
Depois de ter baixado o Git, é necessário configurar o seu nome e e-mail que serão exibidos em seus *commits*, para isso é só digitar no terminal os comandos abaixo.

> Observação: Caso você esteja no Windows, não se esqueça de utilizar o `git bash`, ao invés do `cmd`, pois o `git bash` simula um ambiente Unix, facilitando a forma de trabalhar com Git.

2020-11-07 16:56 UTC, alexandrevicenzi commented on content/posts/2020/aprenda-git-e-github/index.md
> +- **git config --global user.name "Buteco Tecnológico"**
Alterar

```txt
- **git config --global user.name "Buteco Tecnológico"**
```

Para

```txt
`git config --global user.name "Buteco Tecnológico`
```

Fazer isso para todos os comandos abaixo.

2020-11-07 16:56 UTC, alexandrevicenzi commented on content/posts/2020/aprenda-git-e-github/index.md
> +- **git config --global user.name "Buteco Tecnológico"**
Ao fazer isso o texto é formatado como codigo fonte/comandos e não negrito.

2020-11-07 16:56 UTC, alexandrevicenzi commented on content/posts/2020/aprenda-git-e-github/index.md
> +Agora iremos criar uma chave de SSH, com ela conseguimos provar ao GitHub que nós somos os donos da nossa conta, você talvez até já tenha uma chave SSH no seu computador, podemos checar se já existe
colocar ponto entre:

conta, você -> conta. Você

2020-11-07 16:56 UTC, alexandrevicenzi commented on content/posts/2020/aprenda-git-e-github/index.md
> +Agora iremos criar uma chave de SSH, com ela conseguimos provar ao GitHub que nós somos os donos da nossa conta, você talvez até já tenha uma chave SSH no seu computador, podemos checar se já existe
`**".ssh"**` -> `` `.ssh` ``

2020-11-07 16:56 UTC, alexandrevicenzi commented on content/posts/2020/aprenda-git-e-github/index.md
> +Agora iremos criar uma chave de SSH, com ela conseguimos provar ao GitHub que nós somos os donos da nossa conta, você talvez até já tenha uma chave SSH no seu computador, podemos checar se já existe
Ajustar demais comandos para usar o mesmo formato no texto.

2020-11-07 16:56 UTC, alexandrevicenzi commented on content/posts/2020/aprenda-git-e-github/index.md
> +O comando acima irá pedir um nome do arquivo para salvar a chave, não escreva nada e aperte enter (será gerada uma com o nome **"id_rsa"**). Depois, informe uma senha (**passphrase**) e confirme ela.
`**"id_rsa"**` -> `**id_rsa**`

2020-11-07 16:56 UTC, alexandrevicenzi commented on content/posts/2020/aprenda-git-e-github/index.md
> +  Caso o comando **"ls"** retorne algo com a extensão ".pub", você não precisa executar o comando **"ssh-keygen"**. Caso contrário, digite esse comando no seu terminal:
`".pub"` > `**.pub**`

2020-11-07 16:56 UTC, alexandrevicenzi commented on content/posts/2020/aprenda-git-e-github/index.md
> +## Workflow #1
Workflow 1 pode ser mudado para Cenário 1.

2020-11-07 16:56 UTC, alexandrevicenzi commented on content/posts/2020/aprenda-git-e-github/index.md
> +## Workflow #1
Ou Fluxo de trabalho, que é o termo em portugues.

2020-11-07 16:56 UTC, alexandrevicenzi commented on content/posts/2020/aprenda-git-e-github/index.md
> +Mas ainda não acabou por aí, o próximo passo, é você estudar sobre **branches** e como elas funcionam e são usadas. E claro, contribuir com muito código **open source**.
Mas não acabo por aí. O próximo passo é estudar sobre **branches**, entendendo como elas funcionam e são usadas. E claro, contribuir com software livre.

2020-11-10 02:53 UTC, LeoDalcegio commented
Desculpem pelos erros de português, passaram despercebidos mesmo

2020-11-16 20:55 UTC, alexandrevicenzi requested changes
Tem bastante coisa ainda, eu ajustei a formatação, troquei algumas palavras, corrigi alguns erros que ficaram ainda, enfim, é pra estar correto agora.

Esta em https://pastebin.ubuntu.com/p/JBGk79MMvq/

No geral o texto é o mesmo, so tentei deixar mais claro e facil de ler algumas coisas.

2020-11-16 20:58 UTC, alexandrevicenzi commented
Se mandar essas alterações ate amanha eu agendo para dia 18 :)

2020-11-17 10:39 UTC, LeoDalcegio commented
Sim, claro, hoje de meio dia realizo as alterações e te mando.

Bixo, não pensei que ia ser complicado assim pra escrever um artigo, é cheio de detalhes que o cara tem que se atentar, mas curti bastante, dá de aprender muuuito, vou ver se escrevo mais algumas coisas com o tempo, pra tentar me aperfeiçoar mais nisso.

Muito obrigado pela ajuda!

2020-11-17 12:03 UTC, alexandrevicenzi commented
@LeoDalcegio sem stress, é firulinhas pra deixar mais organizado. Outra coisa, leva um tempo pra aprender a escrever artigos, quando mais escreve melhor vai ficando.

Entra no discord, telegram ou algum outro canal que podemos trocar ideias, pode facilitar a revisao :)

2020-11-17 15:00 UTC, LeoDalcegio commented
Showw, entrei no canal do Discord do Buteco já.

2020-11-17 15:26 UTC, alexandrevicenzi approved these changes

2020-11-17 15:27 UTC, alexandrevicenzi commented
@jaswdr não adiciona o prscheduler pq eu quero fazer squash dos commits.

2020-11-18 10:44 UTC, merged

2020-11-18 10:45 UTC, alexandrevicenzi commented
@LeoDalcegio pelo que vi tu mandou PR do teu master, como eu dei squash vai dar ruim, tens que fazer um reset do branch provavelmente.

O ideal seria sempre criar um branch novo para cada artigo, assim não causa conflitos caso seja feito squash no upstream/master.

2020-11-18 11:56 UTC, LeoDalcegio commented
Sim, realmente, deveria ter criado uma branch para o artigo.